package com.lyadirga.bildirimleogren.ui.theme

import androidx.compose.ui.graphics.Color


// 🟢 Green Light Colors
val GreenPrimaryLight = Color(0xFF6D5E0F)
val GreenOnPrimaryLight = Color(0xFFFFFFFF)
val GreenPrimaryContainerLight = Color(0xFFF8E287)
val GreenOnPrimaryContainerLight = Color(0xFF221B00)
val GreenSecondaryLight = Color(0xFF665E40)
val GreenOnSecondaryLight = Color(0xFFFFFFFF)
val GreenSecondaryContainerLight = Color(0xFFEEE2BC)
val GreenOnSecondaryContainerLight = Color(0xFF211B04)
val GreenTertiaryLight = Color(0xFF43664E)
val GreenOnTertiaryLight = Color(0xFFFFFFFF)
val GreenTertiaryContainerLight = Color(0xFFC5ECCE)
val GreenOnTertiaryContainerLight = Color(0xFF00210F)
val GreenErrorLight = Color(0xFFBA1A1A)
val GreenOnErrorLight = Color(0xFFFFFFFF)
val GreenErrorContainerLight = Color(0xFFFFDAD6)
val GreenOnErrorContainerLight = Color(0xFF410002)
val GreenBackgroundLight = Color(0xFFFFF9EE)
val GreenOnBackgroundLight = Color(0xFF1E1B13)
val GreenSurfaceLight = Color(0xFFFFF9EE)
val GreenOnSurfaceLight = Color(0xFF1E1B13)
val GreenSurfaceVariantLight = Color(0xFFEAE2D0)
val GreenOnSurfaceVariantLight = Color(0xFF4B4739)
val GreenOutlineLight = Color(0xFF7C7767)
val GreenOutlineVariantLight = Color(0xFFCDC6B4)
val GreenScrimLight = Color(0xFF000000)
val GreenInverseSurfaceLight = Color(0xFF333027)
val GreenInverseOnSurfaceLight = Color(0xFFF7F0E2)
val GreenInversePrimaryLight = Color(0xFFDBC66E)
val GreenSurfaceDimLight = Color(0xFFE0D9CC)
val GreenSurfaceBrightLight = Color(0xFFFFF9EE)
val GreenSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val GreenSurfaceContainerLowLight = Color(0xFFFAF3E5)
val GreenSurfaceContainerLight = Color(0xFFF4EDDF)
val GreenSurfaceContainerHighLight = Color(0xFFEEE8DA)
val GreenSurfaceContainerHighestLight = Color(0xFFE8E2D4)

// 🟢 Green Dark Colors
val GreenPrimaryDark = Color(0xFFDBC66E)
val GreenOnPrimaryDark = Color(0xFF3A3000)
val GreenPrimaryContainerDark = Color(0xFF534600)
val GreenOnPrimaryContainerDark = Color(0xFFF8E287)
val GreenSecondaryDark = Color(0xFFD1C6A1)
val GreenOnSecondaryDark = Color(0xFF363016)
val GreenSecondaryContainerDark = Color(0xFF4E472A)
val GreenOnSecondaryContainerDark = Color(0xFFEEE2BC)
val GreenTertiaryDark = Color(0xFFA9D0B3)
val GreenOnTertiaryDark = Color(0xFF143723)
val GreenTertiaryContainerDark = Color(0xFF2C4E38)
val GreenOnTertiaryContainerDark = Color(0xFFC5ECCE)
val GreenErrorDark = Color(0xFFFFB4AB)
val GreenOnErrorDark = Color(0xFF690005)
val GreenErrorContainerDark = Color(0xFF93000A)
val GreenOnErrorContainerDark = Color(0xFFFFDAD6)
val GreenBackgroundDark = Color(0xFF15130B)
val GreenOnBackgroundDark = Color(0xFFE8E2D4)
val GreenSurfaceDark = Color(0xFF15130B)
val GreenOnSurfaceDark = Color(0xFFE8E2D4)
val GreenSurfaceVariantDark = Color(0xFF4B4739)
val GreenOnSurfaceVariantDark = Color(0xFFCDC6B4)
val GreenOutlineDark = Color(0xFF969080)
val GreenOutlineVariantDark = Color(0xFF4B4739)
val GreenScrimDark = Color(0xFF000000)
val GreenInverseSurfaceDark = Color(0xFFE8E2D4)
val GreenInverseOnSurfaceDark = Color(0xFF333027)
val GreenInversePrimaryDark = Color(0xFF6D5E0F)
val GreenSurfaceDimDark = Color(0xFF15130B)
val GreenSurfaceBrightDark = Color(0xFF3C3930)
val GreenSurfaceContainerLowestDark = Color(0xFF100E07)
val GreenSurfaceContainerLowDark = Color(0xFF1E1B13)
val GreenSurfaceContainerDark = Color(0xFF222017)
val GreenSurfaceContainerHighDark = Color(0xFF2D2A21)
val GreenSurfaceContainerHighestDark = Color(0xFF38352B)
